name: Check formatting
on:
  merge_group:
  push:
    branches:
      - 'main'
      - 'stable-*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Clone repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Set up Javascript environment
        uses: ./.github/actions/setup-javascript

      - name: Format and show diff for diagnostics
        run: |
          yarn format
          git diff -- \
            app/javascript/mastodon/components/account_header/index.tsx \
            app/javascript/mastodon/features/blue2/right_rail.tsx \
            app/javascript/mastodon/features/custom_homepage/styles.module.scss \
            app/javascript/styles/mastodon-bird-ui/components/_modals.scss
          exit 1
